const Inmuebles = [
  {
    Id: "014",
    Nombre: "Venta Oportunidad",
    Image: "./Images/casa1.png",
    Operacion: "venta",
    TipoInmueble: "Casa",
    Direccion: "Rivera 3058",
    Dormitorios: "2",
    Barrio: "Pocitos",
    Departamento: "Montevideo",
    M2: 150,
    Precio: 1000,
  },

  {
    Id: "001",
    Nombre: "Venta Oportunidad",
    Image: "./Images/casa1.png",
    Operacion: "venta",
    TipoInmueble: "Casa",
    Direccion: "Rivera 3058",
    Dormitorios: "3",
    Barrio: "Pocitos",
    Departamento: "Montevideo",
    M2: 150,
    Precio: 1000,
  },

  {
    Id: "002",
    Nombre: "Alquiler",
    Image: "./Images/casa2.png",
    Operacion: "Alquiler",
    TipoInmueble: "Casa",
    Direccion: "Av Italia 1009",
    Dormitorios: "4",
    Barrio: "Carrasco",
    Departamento: "Montevideo",
    M2: 450,
    Precio: 500,
  },

  {
    Id: "003",
    Nombre: "VENDE!!!!",

    Image: "./Images/casa3.png",
    Operacion: "Venta",
    TipoInmueble: "Casa",
    Direccion: "Obligado 1258",
    Dormitorios: "3",
    Barrio: "Pocitos",
    Departamento: "Montevideo",
    M2: 150,
    Precio: 3000,
  },

  {
    Id: "004",
    Nombre: "Amplio Apartamento",
    Image: "./Images/casa1.png",
    Operacion: "alquiler",
    TipoInmueble: "apartamento",
    Dormitorios: "3",
    Direccion: "Rivera 4532",
    Barrio: "Malvin",
    Departamento: "Montevideo",
    M2: 250,
    Precio: 300,
  },

  {
    Id: "005",
    Nombre: "Terreno para Inversion",
    Image: "./Images/casa2.png",
    Operacion: "venta",
    TipoInmueble: "Terreno",
    Direccion: "Calle Los Pajaros",
    Dormitorios: "0",
    Barrio: "Las Toscas",
    Departamento: "Canelones",
    M2: 1500,
    Precio: 500,
  },

  {
    Id: "006",
    Nombre: "Local Comercial!",
    Image: "./Images/casa3.png",
    Operacion: "venta",
    TipoInmueble: "Local Comercial",
    Direccion: "Porongos 3425",
    Dormitorios: "0",
    Barrio: "Union",
    Departamento: "Montevideo",
    M2: 900,
    Precio: 1000,
  },

  {
    Id: "007",
    Nombre: "Venta Oportunidad",
    Image: "./Images/casa1.png",
    Operacion: "venta",
    TipoInmueble: "Casa",
    Direccion: "Rivera 3058",
    Dormitorios: "1",
    Barrio: "Pocitos",
    Departamento: "Montevideo",
    M2: 150,
    Precio: 1000,
  },

  {
    Id: "010",
    Nombre: "Venta Oportunidad",

    Image: "./Images/casa1.png",
    Operacion: "venta",
    TipoInmueble: "Casa",
    Direccion: "Rivera 3058",
    Dormitorios: "monoambiente",
    Barrio: "Pocitos",
    Departamento: "Montevideo",
    M2: 150,
    Precio: 100000,
  },

  {
    Id: "011",
    Nombre: "Venta Oportunidad",

    Image: "./Images/casa1.png",
    Operacion: "venta",
    TipoInmueble: "Casa",
    Direccion: "Rivera 3058",
    Dormitorios: "2",
    Barrio: "Pocitos",
    Departamento: "Montevideo",
    M2: 150,
    Precio: 100000,
  },
];

export default Inmuebles;
